

/*
    Default RGB Effects
    ref: https://docs.qmk.fm/features/rgb_matrix#additional-configh-options
*/

// #define ENABLE_RGB_MATRIX_SOLID_REACTIVE_SIMPLE	 // Enables RGB_MATRIX_SOLID_REACTIVE_SIMPLE
// #define ENABLE_RGB_MATRIX_SOLID_REACTIVE  // Enables RGB_MATRIX_SOLID_REACTIVE
// #define ENABLE_RGB_MATRIX_SOLID_REACTIVE_WIDE  // Enables RGB_MATRIX_SOLID_REACTIVE_WIDE
// #define ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTIWIDE  // Enables RGB_MATRIX_SOLID_REACTIVE_MULTIWIDE
// #define ENABLE_RGB_MATRIX_SOLID_REACTIVE_CROSS  // Enables RGB_MATRIX_SOLID_REACTIVE_CROSS
// #define ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTICROSS  // Enables RGB_MATRIX_SOLID_REACTIVE_MULTICROSS
// #define ENABLE_RGB_MATRIX_SOLID_REACTIVE_NEXUS  // Enables RGB_MATRIX_SOLID_REACTIVE_NEXUS
// #define ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTINEXUS  // Enables RGB_MATRIX_SOLID_REACTIVE_MULTINEXUS
// #define ENABLE_RGB_MATRIX_SPLASH  // Enables RGB_MATRIX_SPLASH
// #define ENABLE_RGB_MATRIX_MULTISPLASH  // Enables RGB_MATRIX_MULTISPLASH
// #define ENABLE_RGB_MATRIX_SOLID_SPLASH  // Enables RGB_MATRIX_SOLID_SPLASH
#define ENABLE_RGB_MATRIX_SOLID_MULTISPLASH // Enables RGB_MATRIX_SOLID_MULTISPLASH

#define RGB_MATRIX_SOLID_REACTIVE_GRADIENT_MODE
// #define ENABLE_RGB_MATRIX_TYPING_HEATMAP

// for Arrg Blur
// #define LED_MATRIX_FRAMEBUFFER_EFFECTS
// #define LED_HITS_TO_REMEMBER 32
#define RGB_MATRIX_DEFAULT_MODE RGB_MATRIX_SOLID_MULTISPLASH

#define RGB_MATRIX_DEFAULT_SPD 64 // Sets the default animation speed, if none has been set
#define RGB_MATRIX_DEFAULT_HUE 175
#define RGB_MATRIX_DEFAULT_SAT 200

// increase number of layers from 4 to 5
#define DYNAMIC_KEYMAP_LAYER_COUNT 5
